<?php
declare(strict_types=1);

namespace Flavio\Tasks;

use Flavio\Traits\Filesystem;
use WP_REST_Request;
use WP_REST_Response;

/**
 * RobotsTxt class for generating robots.txt
 */
class RobotsTxt {
	use Filesystem;

	/**
	 * Constructor
	 */
	public function __construct() {
		add_action('rest_api_init', [$this, 'register_routes']);
	}

	/**
	 * Register REST API routes
	 */
	public function register_routes(): void {
		register_rest_route('flavio/v1', '/tasks/robotstxt', [
			[
				'methods' => 'GET',
				'callback' => [$this, 'get_robots_txt_content'],
				'permission_callback' => [$this, 'check_admin_permissions'],
			],
			[
				'methods' => 'POST',
				'callback' => [$this, 'create_robots_txt'],
				'permission_callback' => [$this, 'check_admin_permissions'],
			],
		]);
	}

	/**
	 * Check if a user has admin permissions
	 *
	 * @return bool
	 */
	public function check_admin_permissions(): bool {
		return current_user_can('manage_options');
	}

	/**
	 * Get robots.txt content (preview)
	 *
	 * @param WP_REST_Request $request
	 * @return WP_REST_Response
	 */
	public function get_robots_txt_content(WP_REST_Request $request): WP_REST_Response {
		$robots_content = $this->build_robots_txt();

		return new WP_REST_Response([
			'success' => true,
			'content' => $robots_content
		], 200);
	}

	/**
	 * Create robots.txt file
	 *
	 * @param WP_REST_Request $request
	 * @return WP_REST_Response
	 */
	public function create_robots_txt(WP_REST_Request $request): WP_REST_Response {
		// Get WordPress root directory
		$wordpress_root = ABSPATH;

		// Check if we have write permissions in WordPress root
		if (!$this->fs_is_writable($wordpress_root)) {
			return new WP_REST_Response([
				'success' => false,
				'message' => 'Write permissions are required in the WordPress root directory to complete this task.'
			], 200);
		}

		// Generate robots.txt content
		$robots_content = $this->build_robots_txt();

		// Write robots.txt file
		$robots_path = $wordpress_root . 'robots.txt';
		$result = $this->fs_put_contents($robots_path, $robots_content);

		if ($result === false) {
			return new WP_REST_Response([
				'success' => false,
				'message' => 'Failed to write robots.txt file.'
			], 500);
		}

		return new WP_REST_Response([
			'success' => true,
			'message' => 'Robots.txt generated successfully.',
			'file' => 'robots.txt'
		], 200);
	}

	/**
	 * Build robots.txt content
	 *
	 * @return string
	 */
	private function build_robots_txt(): string {
		$content = "# Robots.txt file generated by Flavio\n";
		$content .= "# " . $this->fs_get_utc_datetime() . " UTC\n\n";

		// Default robots.txt rules
		$content .= "User-agent: *\n";
		$content .= "Disallow: /wp-admin/\n";
		$content .= "Allow: /wp-admin/admin-ajax.php\n";
		$content .= "Disallow: /wp-includes/\n";
		$content .= "Disallow: /wp-content/plugins/\n";
		$content .= "Disallow: /wp-content/themes/\n";
		$content .= "Disallow: /wp-content/cache/\n";
		$content .= "Disallow: /trackback/\n";
		$content .= "Disallow: /feed/\n";
		$content .= "Disallow: /comments/\n";
		$content .= "Disallow: /xmlrpc.php\n";
		$content .= "Disallow: *?s=\n";
		$content .= "Disallow: *&s=\n";
		$content .= "Disallow: /search/\n";
		$content .= "Disallow: /author/\n";
		$content .= "Disallow: */attachment/\n";
		$content .= "Disallow: */replytocom=\n";
		$content .= "Disallow: */embed$\n\n";

		// Add sitemap reference if exists
		$sitemap_url = home_url('/sitemap.xml');
		$content .= "Sitemap: " . $sitemap_url . "\n";

		return $content;
	}
}
